"""Add feedback table

Revision ID: ed6f74b61bf6
Revises: 20250817_add_recipe_ing_table
Create Date: 2025-08-23 19:49:52.962513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6f74b61bf6'
down_revision: Union[str, Sequence[str], None] = '20250817_add_recipe_ing_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_email'), 'feedback', ['email'], unique=False)
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.drop_index(op.f('ix_ingredients_name_norm'), table_name='ingredients')
    op.create_index(op.f('ix_ingredients_name_norm'), 'ingredients', ['name_norm'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredients_name_norm'), table_name='ingredients')
    op.create_index(op.f('ix_ingredients_name_norm'), 'ingredients', ['name_norm'], unique=False)
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_email'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
